import { getConnectedPool } from "./db/postgres.js";

export async function ensureAiQueryLogsTable(pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS ai_query_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id TEXT,
      role TEXT,
      question TEXT NOT NULL,
      generated_query TEXT,
      query_status VARCHAR(40) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

export async function writeAiQueryLog({
  user_id = null,
  role = null,
  question = "",
  generated_query = "",
  query_status = "unknown"
} = {}) {
  try {
    const pool = await getConnectedPool();
    await ensureAiQueryLogsTable(pool);
    await pool.query(
      `INSERT INTO ai_query_logs
        (user_id, role, question, generated_query, query_status)
       VALUES (?, ?, ?, ?, ?)`,
      [
        user_id ? String(user_id) : null,
        role || null,
        String(question || ""),
        generated_query ? String(generated_query) : null,
        String(query_status || "unknown")
      ]
    );
    return { ok: true };
  } catch (error) {
    console.warn("AI query log skipped:", error.message);
    return { ok: false, error };
  }
}
